/**
 * Produtos para Explorar / "Produtos que você pode comprar".
 * Títulos em português e categorias para preview na home.
 */
export const EXPLORAR_PRODUCTS = [
  { url: "https://weidian.com/item.html?itemID=7392755626", titlePt: "Casaco térmico inverno esportivo 1014", priceCny: 289, category: "moda" as const },
  { url: "https://weidian.com/item.html?itemID=7389113468", titlePt: "Modelo A-3 P2-0102", priceCny: 55, category: "outros" as const },
  { url: "https://weidian.com/item.html?itemID=7388235958", titlePt: "Tênis Reebok 4 retro", priceCny: 250, category: "moda" as const },
  { url: "https://weidian.com/item.html?itemID=7386577527", titlePt: "Tênis 2024 4S Retro Sneakers", priceCny: 280, category: "moda" as const },
  { url: "https://weidian.com/item.html?itemID=7388498976", titlePt: "Tênis M 9060 casual", priceCny: 280, category: "moda" as const },
  { url: "https://weidian.com/item.html?itemID=7399162790", titlePt: "Relógio masculino qualidade premium", priceCny: 380, category: "acessorios" as const },
  { url: "https://weidian.com/item.html?itemID=7387922746", titlePt: "Tênis UG 2021", priceCny: 270, category: "moda" as const },
  { url: "https://weidian.com/item.html?itemID=7626154952", titlePt: "iPhone 17 Pro Max 512GB", priceCny: 1299, category: "eletronicos" as const },
  { url: "https://weidian.com/item.html?itemID=7392316254", titlePt: "Bolsa fashion unissex", priceCny: 69, category: "acessorios" as const },
  { url: "https://weidian.com/item.html?itemID=7626225818", titlePt: "AirPods 4 com case USB-C", priceCny: 119, category: "eletronicos" as const },
  { url: "https://weidian.com/item.html?itemID=7386330489", titlePt: "Tênis casal esportivo casual", priceCny: 520, category: "moda" as const },
  { url: "https://weidian.com/item.html?itemID=7569991217", titlePt: "Jaqueta corta-vento curta brilhante", priceCny: 960, category: "moda" as const },
  { url: "https://weidian.com/item.html?itemID=7426164888", titlePt: "Jaqueta down jacket", priceCny: 280, category: "moda" as const },
  { url: "https://weidian.com/item.html?itemID=7624160803", titlePt: "AirPods Max USB-C", priceCny: 699, category: "eletronicos" as const },
  { url: "https://weidian.com/item.html?itemID=7534086600", titlePt: "Tênis infantil LYWD couro", priceCny: 258, category: "moda" as const },
  { url: "https://weidian.com/item.html?itemID=7571968062", titlePt: "Bota coturno clássica 1AX", priceCny: 270, category: "moda" as const },
  { url: "https://weidian.com/item.html?itemID=7632728799", titlePt: "Apple Pencil 2ª geração", priceCny: 298, category: "eletronicos" as const },
  { url: "https://weidian.com/item.html?itemID=7623936288", titlePt: "AirPods Pro 3ª geração MagSafe USB-C", priceCny: 129, category: "eletronicos" as const },
  { url: "https://weidian.com/item.html?itemID=7542699356", titlePt: "Tênis basquete J4 antiderrapante", priceCny: 888, category: "moda" as const },
  { url: "https://weidian.com/item.html?itemID=7571961944", titlePt: "Botas curtas couro", priceCny: 228, category: "moda" as const },
  { url: "https://weidian.com/item.html?itemID=7556952783", titlePt: "Calça jeans PU cropped com strass", priceCny: 348, category: "moda" as const },
  { url: "https://weidian.com/item.html?itemID=7388734828", titlePt: "Calça jeans PULL variedade", priceCny: 238, category: "moda" as const },
  { url: "https://weidian.com/item.html?itemID=7386662157", titlePt: "Tênis Face1 Low XQ", priceCny: 120, category: "moda" as const },
  { url: "https://weidian.com/item.html?itemID=7566796357", titlePt: "Casaco longo com capuz premium", priceCny: 590, category: "moda" as const },
  { url: "https://weidian.com/item.html?itemID=7428474671", titlePt: "Camiseta B585", priceCny: 99, category: "moda" as const },
  { url: "https://weidian.com/item.html?itemID=7570022623", titlePt: "Casaco x219 corta-vento", priceCny: 1300, category: "moda" as const },
  { url: "https://weidian.com/item.html?itemID=7402520780", titlePt: "Camiseta Godspe verão", priceCny: 118, category: "moda" as const },
  { url: "https://weidian.com/item.html?itemID=7572611824", titlePt: "Colete grosso fashion", priceCny: 236, category: "moda" as const },
  { url: "https://weidian.com/item.html?itemID=7576909422", titlePt: "Camiseta Corteiz 5 anos", priceCny: 160, category: "moda" as const },
  { url: "https://weidian.com/item.html?itemID=7421534661", titlePt: "Tênis plataforma casual", priceCny: 420, category: "moda" as const },
  { url: "https://weidian.com/item.html?itemID=7392935064", titlePt: "Óculos de sol chat UV", priceCny: 230, category: "acessorios" as const },
  { url: "https://weidian.com/item.html?itemID=7388253928", titlePt: "Tênis fashion", priceCny: 480, category: "moda" as const },
  { url: "https://weidian.com/item.html?itemID=7390473789", titlePt: "Bolsa 1014 all-in-one", priceCny: 59, category: "acessorios" as const },
  { url: "https://weidian.com/item.html?itemID=7418314380", titlePt: "Tênis Vaporwaffle casual", priceCny: 270, category: "moda" as const },
  { url: "https://weidian.com/item.html?itemID=7393295696", titlePt: "Perfume 100ml masculino", priceCny: 108, category: "beleza" as const },
  { url: "https://weidian.com/item.html?itemID=7391267669", titlePt: "Pulseira 5A cubic zircônia", priceCny: 90, category: "acessorios" as const },
  { url: "https://weidian.com/item.html?itemID=7392304288", titlePt: "Bolsa L fashion K4", priceCny: 385, category: "acessorios" as const },
  { url: "https://weidian.com/item.html?itemID=7387308437", titlePt: "Controle 2021 P&S 5", priceCny: 520, category: "eletronicos" as const },
  { url: "https://weidian.com/item.html?itemID=7400912230", titlePt: "Relógio masculino premium", priceCny: 1288, category: "acessorios" as const },
  { url: "https://weidian.com/item.html?itemID=7400896120", titlePt: "Fone TOPultra 07", priceCny: 245, category: "eletronicos" as const },
  { url: "https://weidian.com/item.html?itemID=7400882622", titlePt: "Relógio automático clássico", priceCny: 1688, category: "acessorios" as const },
  // Novos links
  { url: "https://weidian.com/item.html?itemID=7399176632", titlePt: "Relógio 132415", priceCny: 308, category: "acessorios" as const },
  { url: "https://weidian.com/item.html?itemID=7515649491", titlePt: "Tênis casual placa", priceCny: 369, category: "moda" as const },
  { url: "https://weidian.com/item.html?itemID=7494600429", titlePt: "Moletom esportivo feminino manga longa", priceCny: 120, category: "moda" as const },
  { url: "https://weidian.com/item.html?itemID=7424577749", titlePt: "Sandália/chinelo unissex", priceCny: 118, category: "moda" as const },
  { url: "https://weidian.com/item.html?itemID=7425303732", titlePt: "Mala de viagem addTravel", priceCny: 199, category: "acessorios" as const },
  { url: "https://weidian.com/item.html?itemID=7395989993", titlePt: "Camiseta futebol S manga curta", priceCny: 79, category: "moda" as const },
  { url: "https://weidian.com/item.html?itemID=7424638812", titlePt: "Tênis esportivo confortável", priceCny: 260, category: "moda" as const },
  { url: "https://weidian.com/item.html?itemID=7386307133", titlePt: "Tênis OG casual", priceCny: 240, category: "moda" as const },
  { url: "https://weidian.com/item.html?itemID=7425201304", titlePt: "Anel ajustável com strass", priceCny: 88, category: "acessorios" as const },
  { url: "https://weidian.com/item.html?itemID=7464669388", titlePt: "D*S HD07", priceCny: 545, category: "eletronicos" as const },
  { url: "https://weidian.com/item.html?itemID=7424613442", titlePt: "Produto Weidian", priceCny: null, category: "outros" as const },
  { url: "https://weidian.com/item.html?itemID=7464717164", titlePt: "Relógio automático masculino data dual time", priceCny: 2680, category: "acessorios" as const },
  { url: "https://weidian.com/item.html?itemID=7432952811", titlePt: "Maiô fashion", priceCny: 139, category: "moda" as const },
  { url: "https://weidian.com/item.html?itemID=7423321207", titlePt: "Bolsa feminina quadrada minimalista", priceCny: 136, category: "acessorios" as const },
  { url: "https://weidian.com/item.html?itemID=7464711086", titlePt: "Relógio Hermès S8 1:1", priceCny: 460, category: "acessorios" as const },
];
