[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm ci", "npx playwright install chromium"]

[phases.build]
cmds = ["npx prisma generate", "npm run build"]

[phases.run]
cmd = "npx prisma migrate deploy && node dist/index.js"
